2025-06-18 16:21:59,056 - __main__ - INFO - Starting bot...
2025-06-18 16:21:59,058 - aiogram.dispatcher - INFO - Start polling
2025-06-18 16:23:09,979 - aiogram.event - INFO - Update id=679473974 is handled. Duration 718 ms by bot id=8052721063
2025-06-18 16:23:11,855 - aiogram.event - INFO - Update id=679473975 is handled. Duration 218 ms by bot id=8052721063
2025-06-18 16:23:32,112 - aiogram.event - INFO - Update id=679473976 is not handled. Duration 453 ms by bot id=8052721063
2025-06-18 16:23:32,112 - aiogram.event - ERROR - Cause exception while process update id=679473976 by bot id=8052721063
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 613
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\GarantBot\main.py", line 828, in help_command
    await message.answer(help_text, parse_mode="Markdown")
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\client\bot.py", line 492, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\client\session\base.py", line 248, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\client\session\aiohttp.py", line 178, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 613
2025-06-18 16:23:51,998 - aiogram.event - INFO - Update id=679473977 is handled. Duration 625 ms by bot id=8052721063
2025-06-18 16:24:01,312 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [WinError 1236] Подключение к сети было разорвано локальной системой
2025-06-18 16:24:01,313 - aiogram.dispatcher - WARNING - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 8052721063)
2025-06-18 16:24:24,115 - aiogram.dispatcher - INFO - Connection established (tryings = 1, bot id = 8052721063)
2025-06-18 16:25:20,671 - aiogram.event - INFO - Update id=679473978 is not handled. Duration 56546 ms by bot id=8052721063
2025-06-18 16:25:42,532 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [WinError 1236] Подключение к сети было разорвано локальной системой
2025-06-18 16:25:42,532 - aiogram.dispatcher - WARNING - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 8052721063)
2025-06-18 16:25:42,618 - aiogram.event - INFO - Update id=679473979 is not handled. Duration 15468 ms by bot id=8052721063
2025-06-18 16:25:43,622 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [Сетевая папка недоступна. За информацией о разрешении проблем в сети обратитесь к справочной системе Windows]
2025-06-18 16:25:43,623 - aiogram.dispatcher - WARNING - Sleep for 1.300480 seconds and try again... (tryings = 1, bot id = 8052721063)
2025-06-18 16:25:45,122 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [WinError 1236] Подключение к сети было разорвано локальной системой
2025-06-18 16:25:45,122 - aiogram.dispatcher - WARNING - Sleep for 1.555795 seconds and try again... (tryings = 2, bot id = 8052721063)
2025-06-18 16:25:56,405 - aiogram.dispatcher - INFO - Connection established (tryings = 3, bot id = 8052721063)
2025-06-18 16:25:56,736 - aiogram.event - INFO - Update id=679473980 is handled. Duration 327 ms by bot id=8052721063
2025-06-18 16:26:04,699 - aiogram.event - INFO - Update id=679473981 is not handled. Duration 0 ms by bot id=8052721063
2025-06-18 16:26:04,699 - aiogram.event - ERROR - Cause exception while process update id=679473981 by bot id=8052721063
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\GarantBot\main.py", line 200, in balance_menu
    if user["banned"]:
       ~~~~^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2025-06-18 16:26:40,414 - aiogram.event - INFO - Update id=679473982 is handled. Duration 390 ms by bot id=8052721063
2025-06-18 16:26:46,491 - aiogram.event - INFO - Update id=679473983 is handled. Duration 172 ms by bot id=8052721063
2025-06-18 16:27:35,086 - aiogram.event - INFO - Update id=679473984 is handled. Duration 922 ms by bot id=8052721063
2025-06-18 16:27:56,691 - aiogram.event - INFO - Update id=679473985 is handled. Duration 500 ms by bot id=8052721063
2025-06-18 16:28:01,913 - aiogram.event - INFO - Update id=679473986 is handled. Duration 218 ms by bot id=8052721063
2025-06-18 16:28:06,519 - aiogram.event - INFO - Update id=679473987 is handled. Duration 203 ms by bot id=8052721063
2025-06-18 16:28:10,631 - aiogram.event - INFO - Update id=679473988 is handled. Duration 203 ms by bot id=8052721063
2025-06-18 16:28:12,782 - aiogram.event - INFO - Update id=679473989 is handled. Duration 219 ms by bot id=8052721063
2025-06-18 16:28:21,879 - aiogram.event - INFO - Update id=679473990 is handled. Duration 406 ms by bot id=8052721063
2025-06-18 16:28:24,386 - aiogram.event - INFO - Update id=679473991 is handled. Duration 343 ms by bot id=8052721063
2025-06-18 16:28:25,986 - aiogram.event - INFO - Update id=679473992 is handled. Duration 202 ms by bot id=8052721063
2025-06-18 16:28:29,563 - aiogram.event - INFO - Update id=679473993 is handled. Duration 500 ms by bot id=8052721063
2025-06-18 16:28:31,508 - aiogram.event - INFO - Update id=679473994 is handled. Duration 312 ms by bot id=8052721063
2025-06-18 16:28:34,178 - aiogram.event - INFO - Update id=679473995 is handled. Duration 217 ms by bot id=8052721063
2025-06-18 16:28:35,395 - aiogram.event - INFO - Update id=679473996 is handled. Duration 203 ms by bot id=8052721063
2025-06-18 16:28:36,829 - aiogram.event - INFO - Update id=679473997 is handled. Duration 202 ms by bot id=8052721063
2025-06-18 16:28:38,985 - aiogram.event - INFO - Update id=679473998 is handled. Duration 406 ms by bot id=8052721063
2025-06-18 16:29:50,129 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [WinError 1236] Подключение к сети было разорвано локальной системой
2025-06-18 16:29:50,130 - aiogram.dispatcher - WARNING - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 8052721063)
2025-06-18 16:30:03,189 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
2025-06-18 16:30:03,190 - aiogram.dispatcher - WARNING - Sleep for 1.618291 seconds and try again... (tryings = 1, bot id = 8052721063)
2025-06-18 16:30:23,131 - aiogram.dispatcher - INFO - Connection established (tryings = 2, bot id = 8052721063)
2025-06-18 16:37:11,078 - aiogram.dispatcher - INFO - Polling stopped
2025-06-18 16:37:11,362 - __main__ - INFO - Bot stopped by user
2025-06-18 16:37:11,362 - __main__ - INFO - Bot shutdown complete
2025-06-18 16:42:41,310 - __main__ - INFO - Starting bot...
2025-06-18 16:42:41,313 - aiogram.dispatcher - INFO - Start polling
2025-06-18 16:42:53,300 - aiogram.event - INFO - Update id=679473999 is handled. Duration 577 ms by bot id=8052721063
2025-06-18 16:42:58,317 - aiogram.event - INFO - Update id=679474000 is handled. Duration 93 ms by bot id=8052721063
2025-06-18 16:42:59,155 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [WinError 1236] Подключение к сети было разорвано локальной системой
2025-06-18 16:42:59,157 - aiogram.dispatcher - WARNING - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 8052721063)
2025-06-18 16:43:00,385 - aiogram.dispatcher - INFO - Connection established (tryings = 1, bot id = 8052721063)
2025-06-18 16:43:09,453 - aiogram.event - INFO - Update id=679474001 is handled. Duration 9062 ms by bot id=8052721063
2025-06-18 16:43:16,603 - aiogram.event - INFO - Update id=679474002 is handled. Duration 156 ms by bot id=8052721063
2025-06-18 16:43:22,867 - aiogram.event - INFO - Update id=679474003 is handled. Duration 203 ms by bot id=8052721063
2025-06-18 16:43:27,067 - aiogram.event - INFO - Update id=679474004 is handled. Duration 77 ms by bot id=8052721063
2025-06-18 16:43:35,298 - aiogram.event - INFO - Update id=679474005 is handled. Duration 77 ms by bot id=8052721063
2025-06-18 16:43:36,924 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [WinError 1236] Подключение к сети было разорвано локальной системой
2025-06-18 16:43:36,925 - aiogram.dispatcher - WARNING - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 8052721063)
2025-06-18 16:43:37,938 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
2025-06-18 16:43:37,938 - aiogram.dispatcher - WARNING - Sleep for 1.333131 seconds and try again... (tryings = 1, bot id = 8052721063)
2025-06-18 16:43:39,310 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
2025-06-18 16:43:39,310 - aiogram.dispatcher - WARNING - Sleep for 1.909338 seconds and try again... (tryings = 2, bot id = 8052721063)
2025-06-18 16:43:41,228 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
2025-06-18 16:43:41,228 - aiogram.dispatcher - WARNING - Sleep for 2.565085 seconds and try again... (tryings = 3, bot id = 8052721063)
2025-06-18 16:43:46,253 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [WinError 1236] Подключение к сети было разорвано локальной системой
2025-06-18 16:43:46,253 - aiogram.dispatcher - WARNING - Sleep for 3.337130 seconds and try again... (tryings = 4, bot id = 8052721063)
2025-06-18 16:43:47,651 - aiogram.dispatcher - INFO - Polling stopped
2025-06-18 16:43:47,932 - __main__ - INFO - Bot stopped by user
2025-06-18 16:43:47,932 - __main__ - INFO - Bot shutdown complete
2025-06-18 16:43:53,355 - __main__ - INFO - Starting bot...
2025-06-18 16:43:53,356 - aiogram.dispatcher - INFO - Start polling
2025-06-18 16:43:55,995 - aiogram.event - INFO - Update id=679474006 is handled. Duration 360 ms by bot id=8052721063
2025-06-18 16:43:59,606 - aiogram.event - INFO - Update id=679474007 is handled. Duration 139 ms by bot id=8052721063
2025-06-18 16:44:08,665 - aiogram.event - INFO - Update id=679474008 is handled. Duration 110 ms by bot id=8052721063
2025-06-18 16:44:13,816 - aiogram.event - INFO - Update id=679474009 is not handled. Duration 16 ms by bot id=8052721063
2025-06-18 16:44:16,245 - aiogram.event - INFO - Update id=679474010 is handled. Duration 93 ms by bot id=8052721063
2025-06-18 16:44:20,446 - aiogram.event - INFO - Update id=679474011 is handled. Duration 77 ms by bot id=8052721063
2025-06-18 16:44:22,900 - aiogram.event - INFO - Update id=679474012 is handled. Duration 109 ms by bot id=8052721063
2025-06-18 16:44:38,973 - aiogram.event - INFO - Update id=679474013 is handled. Duration 358 ms by bot id=8052721063
2025-06-18 16:44:42,050 - aiogram.event - INFO - Update id=679474014 is handled. Duration 280 ms by bot id=8052721063
2025-06-18 16:44:54,397 - aiogram.event - INFO - Update id=679474015 is handled. Duration 156 ms by bot id=8052721063
2025-06-18 16:45:08,787 - aiogram.event - INFO - Update id=679474016 is handled. Duration 93 ms by bot id=8052721063
2025-06-18 16:45:25,488 - aiogram.event - INFO - Update id=679474017 is not handled. Duration 16 ms by bot id=8052721063
2025-06-18 16:45:42,902 - aiogram.event - INFO - Update id=679474018 is handled. Duration 344 ms by bot id=8052721063
2025-06-18 16:46:01,203 - aiogram.event - INFO - Update id=679474019 is handled. Duration 406 ms by bot id=8052721063
2025-06-18 16:46:15,860 - aiogram.event - INFO - Update id=679474020 is handled. Duration 202 ms by bot id=8052721063
2025-06-18 16:46:19,335 - aiogram.event - INFO - Update id=679474021 is handled. Duration 93 ms by bot id=8052721063
2025-06-18 16:46:59,548 - aiogram.event - INFO - Update id=679474022 is handled. Duration 218 ms by bot id=8052721063
2025-06-18 16:47:01,959 - aiogram.event - INFO - Update id=679474023 is handled. Duration 172 ms by bot id=8052721063
2025-06-18 16:47:05,873 - aiogram.event - INFO - Update id=679474024 is handled. Duration 266 ms by bot id=8052721063
2025-06-18 16:47:10,542 - aiogram.event - INFO - Update id=679474025 is handled. Duration 110 ms by bot id=8052721063
2025-06-18 16:47:41,775 - aiogram.event - INFO - Update id=679474026 is handled. Duration 391 ms by bot id=8052721063
2025-06-18 16:48:07,150 - aiogram.dispatcher - INFO - Polling stopped
2025-06-18 16:48:07,415 - __main__ - INFO - Bot stopped by user
2025-06-18 16:48:07,415 - __main__ - INFO - Bot shutdown complete
2025-06-18 22:42:50,684 - __main__ - INFO - Database initialized
2025-06-18 22:42:51,300 - __main__ - INFO - Bot starting...
2025-06-18 22:42:51,301 - aiogram.dispatcher - INFO - Start polling
2025-06-18 22:42:51,966 - aiogram.dispatcher - INFO - Run polling for bot @JodyGarant_Bot id=8052721063 - 'рќ™…рќ™¤рќ™™рќ™® рќ™‚рќ™–рќ™§рќ™–рќ™Јрќ™©'
2025-06-18 22:43:02,357 - __main__ - INFO - Showed main menu to 7586266147
2025-06-18 22:43:02,358 - __main__ - INFO - New session started for 7586266147
2025-06-18 22:43:02,358 - aiogram.event - INFO - Update id=679474027 is handled. Duration 812 ms by bot id=8052721063
2025-06-18 22:43:05,446 - __main__ - INFO - User search initiated by 7586266147
2025-06-18 22:43:05,447 - aiogram.event - INFO - Update id=679474028 is handled. Duration 437 ms by bot id=8052721063
2025-06-18 22:43:11,973 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [WinError 1236] РџРѕРґРєР»СЋС‡РµРЅРёРµ Рє СЃРµС‚Рё Р±С‹Р»Рѕ СЂР°Р·РѕСЂРІР°РЅРѕ Р»РѕРєР°Р»СЊРЅРѕР№ СЃРёСЃС‚РµРјРѕР№
2025-06-18 22:43:11,974 - aiogram.dispatcher - WARNING - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 8052721063)
2025-06-18 22:43:15,423 - aiogram.dispatcher - INFO - Connection established (tryings = 1, bot id = 8052721063)
2025-06-18 22:43:15,835 - __main__ - INFO - User found: 8022396358 for 7586266147
2025-06-18 22:43:15,836 - aiogram.event - INFO - Update id=679474029 is handled. Duration 422 ms by bot id=8052721063
2025-06-18 22:43:30,516 - aiogram.event - INFO - Update id=679474030 is handled. Duration 156 ms by bot id=8052721063
2025-06-18 22:43:35,153 - aiogram.event - INFO - Update id=679474031 is handled. Duration 94 ms by bot id=8052721063
2025-06-18 22:43:42,472 - __main__ - INFO - Deal DL20250618224342-09PI5H created by 7586266147
2025-06-18 22:43:42,473 - aiogram.event - INFO - Update id=679474032 is handled. Duration 358 ms by bot id=8052721063
2025-06-18 22:43:44,742 - __main__ - INFO - Updated balance for 7586266147: -30.0 USDT
2025-06-18 22:43:45,360 - __main__ - INFO - Deal DL20250618224342-09PI5H confirmed by 7586266147
2025-06-18 22:43:45,360 - aiogram.event - INFO - Update id=679474033 is handled. Duration 608 ms by bot id=8052721063
2025-06-18 22:43:58,220 - aiogram.event - INFO - Update id=679474034 is not handled. Duration 0 ms by bot id=8052721063
2025-06-18 22:44:15,509 - __main__ - INFO - Updated balance for 8022396358: 30.0 USDT
2025-06-18 22:44:16,463 - __main__ - INFO - Deal DL20250618224342-09PI5H completed by 8022396358
2025-06-18 22:44:16,463 - aiogram.event - INFO - Update id=679474035 is handled. Duration 953 ms by bot id=8052721063
2025-06-18 22:45:43,481 - __main__ - INFO - Help requested by 8022396358
2025-06-18 22:45:43,482 - aiogram.event - INFO - Update id=679474036 is handled. Duration 297 ms by bot id=8052721063
2025-06-18 22:45:52,810 - __main__ - INFO - Support requested by 8022396358
2025-06-18 22:45:52,810 - aiogram.event - INFO - Update id=679474037 is handled. Duration 311 ms by bot id=8052721063
2025-06-18 22:45:57,748 - __main__ - INFO - Support message from 8022396358 forwarded to admin
2025-06-18 22:45:57,748 - aiogram.event - INFO - Update id=679474038 is handled. Duration 391 ms by bot id=8052721063
2025-06-18 22:45:59,564 - __main__ - INFO - Balance menu shown to 8022396358
2025-06-18 22:45:59,564 - aiogram.event - INFO - Update id=679474039 is handled. Duration 155 ms by bot id=8052721063
2025-06-18 22:46:02,847 - aiogram.event - INFO - Update id=679474040 is handled. Duration 264 ms by bot id=8052721063
2025-06-18 22:49:11,308 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [WinError 1236] РџРѕРґРєР»СЋС‡РµРЅРёРµ Рє СЃРµС‚Рё Р±С‹Р»Рѕ СЂР°Р·РѕСЂРІР°РЅРѕ Р»РѕРєР°Р»СЊРЅРѕР№ СЃРёСЃС‚РµРјРѕР№
2025-06-18 22:49:11,308 - aiogram.dispatcher - WARNING - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 8052721063)
2025-06-18 22:49:23,234 - aiogram.dispatcher - INFO - Connection established (tryings = 1, bot id = 8052721063)
2025-06-18 22:50:45,092 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2025-06-18 22:50:45,092 - aiogram.dispatcher - WARNING - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 8052721063)
2025-06-18 22:50:57,259 - aiogram.dispatcher - INFO - Connection established (tryings = 1, bot id = 8052721063)
2025-06-18 22:51:27,472 - aiogram.dispatcher - INFO - Polling stopped
2025-06-18 22:51:27,734 - __main__ - INFO - Bot shutting down...
2025-06-18 22:51:27,771 - aiogram.dispatcher - INFO - Polling stopped for bot @JodyGarant_Bot id=8052721063 - 'рќ™…рќ™¤рќ™™рќ™® рќ™‚рќ™–рќ™§рќ™–рќ™Јрќ™©'
2025-06-18 22:51:27,773 - __main__ - INFO - Bot stopped by user
2025-06-18 22:51:27,773 - __main__ - INFO - Bot shutdown complete
2025-06-19 11:22:11,089 - __main__ - INFO - Database initialized
2025-06-19 11:26:45,357 - __main__ - INFO - Database initialized
2025-06-19 11:51:42,022 - __main__ - INFO - Database initialized
